start_pose_num: 0
end_pose_num: 50 
headYaw_min: 0.0
headYaw_max: 0.0
headYaw_step: 0.0
headPitch_min: 0.0
haedPitch_max: 0.0
headPitch_step: 0.0
marker_color_r: 255
marker_color_g: 0
marker_color_b: 0
find_marker: false
move_marker_to_corners: false