chain_name: larm
chain_root: HeadPitch_link
chain_tip: l_wrist
marker_type: checkerboard       # checkerboard, aruco, circle, color
marker_frame: LMarker_frame

marker_transform_source: urdf   # 'tf' or 'urdf' (optional; if not set, default is 'urdf')

# checkerboard specific parameters
checkerboard_rows: 4            # optional; if not set, default is 4 WATCH OUT: This is NOT the usual internal 
checkerboard_columns: 4         # optional; if not set, default is 4 WATCH OUT: number of corners but number of squares!
checkerboard_squarelength: 7.5   # optional; side length of one square of the checkerboard in [mm]

# aruco marker specific parameters
aruco_markersize: 20            # optional; side length of the aruco marker in [mm]
