rarm001:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.315502, 0.0558941, -0.251866, 0.161629, 0.0823757, 0.987163, -0.168878]

rarm002:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.206759, -0.680585, 0.893652, 0.242086, 1.55211, 1.17185, -0.831946]

rarm003:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.305578, -0.615236, 0.716552, 0.0359781, 1.39799, 1.09684, -0.772039]

rarm004:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0414993, -0.651071, 1.01838, -0.880256, 0.362602, 1.29679, -0.238194]

rarm005:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.232045, -0.792788, 0.885031, -0.833393, 0.981235, 1.37198, -0.512598]

rarm006:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.179733, -0.369787, 0.919475, -0.199988, 1.35083, 1.01262, -0.599703]

rarm007:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.470128, -0.689758, 0.474774, -0.916152, 0.784415, 1.26523, 0.174105]

rarm008:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0380074, -0.50368, 1.12352, 0.112176, 1.53655, 1.38197, -1.09659]

rarm009:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0591506, -0.615291, 0.859193, -0.565494, 0.619494, 1.13968, -0.209159]

rarm010:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.189362, -0.307792, 0.795256, -0.154011, 1.04012, 1.13004, -0.800478]

rarm011:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.269802, -0.339559, 0.630386, -0.0613905, 1.08646, 1.16665, -0.668132]

rarm012:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.152317, -0.432727, 0.813734, -0.49853, 0.837216, 1.40026, -0.491314]

rarm013:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.171226, -0.404803, 0.698282, -0.504414, 0.63595, 0.904314, -0.013299]

rarm014:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.166181, -0.50073, 0.989443, -0.328837, 0.796587, 1.29706, -0.51802]

rarm015:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.464916, -0.688591, -0.463018, -0.950006, -0.492944, 1.14275, 0.0601875]

rarm016:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.184044, -0.344903, 0.506026, 0.0330464, 0.86478, 0.843617, -0.431214]

rarm017:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.207067, -0.369122, 0.548155, -0.444008, 0.53677, 1.20897, -0.122695]

rarm018:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.526524, -0.547011, -0.21896, -0.808842, -0.0465062, 1.00625, -0.181662]

rarm019:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.328054, -0.507797, 0.590485, -0.614768, 0.693243, 1.19655, 0.151425]

rarm020:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.165228, -0.792231, 1.12615, -0.72627, 0.0584186, 1.33856, 0.263834]

rarm021:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.338729, -0.785972, 1.36912, -0.989287, 1.23603, 1.48893, 0.0439896]

rarm022:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.115662, -0.644215, 1.24368, -0.466253, 1.28119, 1.22262, -0.479846]

rarm023:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.341983, -0.757252, 0.213968, -0.829069, -0.0213377, 1.12197, 0.0644447]

rarm024:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.471285, -0.753539, -0.215103, -0.935236, 0.0386069, 1.19864, -0.1553]

rarm025:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.456225, -1.06392, 0.917557, -0.670583, 1.59206, 1.34234, -0.137849]

rarm026:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0512079, -0.510681, 1.08911, -0.46478, 0.695501, 1.40306, 0.113753]

rarm027:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.38683, -0.924095, 0.952483, -0.692094, 1.77193, 1.39464, -0.847177]

rarm028:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0428657, -0.458428, 0.968745, -0.247287, 1.53639, 1.22011, -0.830832]

rarm029:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.126175, -0.813809, 0.809917, -0.893044, -0.129667, 1.2928, -0.0592281]

rarm030:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.0078115, -0.291046, 0.48315, -0.251493, 0.420582, 1.15261, -0.471911]

rarm031:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.463481, -0.658842, 0.275585, -0.702527, 0.882769, 0.971598, -0.216431]

rarm032:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.292121, -0.993973, 1.1458, -0.597361, 1.445, 1.23541, -0.353239]

rarm033:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.301016, -0.487607, 0.44958, -0.405727, 0.85189, 1.13872, -0.000799588]

rarm034:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.404865, -0.730261, 0.725087, -0.636992, 1.64741, 1.17148, -0.67277]

rarm035:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.444727, -0.543625, 0.524798, -0.394724, 1.25564, 0.991633, -0.364948]

rarm036:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0481362, -0.362687, 1.02187, -0.289701, 1.14699, 1.05368, -0.845836]

rarm037:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.297407, -0.416486, -0.0199659, -0.434601, -0.05369, 1.00382, -0.0153378]

rarm038:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.453682, -0.333971, 0.101565, -0.399691, 0.24699, 1.24276, -0.0417954]

rarm039:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0410451, -0.447714, 1.0287, 0.0303856, 1.56751, 1.11512, -0.716851]

rarm040:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0679116, -0.525421, 1.03272, -0.384113, 0.790568, 1.12866, -0.126074]

rarm041:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0177672, -0.944585, 0.909868, -0.654366, 0.289894, 1.41831, 0.419786]

rarm042:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.0647607, -0.443371, 0.0749071, -0.444837, -0.611204, 1.44796, 0.182735]

rarm043:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.210806, -0.688857, 0.649327, -0.713449, -0.274245, 1.28083, -0.0688572]

rarm044:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.50507, -0.796264, -0.0820943, -1.01367, 0.305851, 1.30278, -0.413043]

rarm045:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.425666, -0.802492, -0.518128, -1.11219, -0.732314, 1.36889, 0.182573]

rarm046:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.300305, -0.854079, 0.542299, -0.82219, 1.00262, 1.32386, -0.627406]

rarm047:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.490238, -0.769626, 0.842983, -0.710038, 1.6584, 1.39243, -0.538143]

rarm048:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.352171, -0.218732, 0.177144, -0.166336, 0.144501, 0.729428, -0.1196]

rarm049:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [0.194758, -0.799666, 0.786993, -0.623996, -0.227341, 1.3507, -0.0645389]

rarm050:
  joint_names: ["HeadPitch", "HeadYaw", "RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw"]
  time_from_start: 1.0
  positions: [-0.373196, -0.81093, 0.898881, -0.623909, 1.92552, 1.35477, -0.691012]

